- hosts: firewalls
  connection: httpapi
  collections:
    - fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 8443

  tasks:
    - name: Include Ansible Vault Token Data
      include_vars:
        file: "/etc/ansible/vault/secret.yml"

    - name: Backup a virtual domain.
      fortinet.fortios.fortios_monitor:
        access_token: "{{ firewall_api_key }}"
        selector: 'backup.system.config'
        vdom: "{{ vdom }}"
        params:
          scope: 'global'
      register: backupinfo

    - name: Get current date and time
      set_fact:
        timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

    - name: Save the backup information.
      copy:
        content: '{{ backupinfo.meta.raw }}'
        dest: '/configs/res-phy-prd-fwp_backup_{{ timestamp }}.conf'
