---
- name: Update Raspberry Pi Servers and Send Email
  hosts: raspi_servers
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  vars:
    smtp_relay_host: ""
    smtp_relay_port: 
    smtp_sender: ""
    smtp_recipient: ""
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Set current date and time
      set_fact:
        timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

    - name: Send email with update results
      community.general.mail:
        host: "{{ smtp_relay_host }}"
        port: "{{ smtp_relay_port }}"
        sender: "{{ smtp_sender }}"
        to: "{{ smtp_recipient }}"
        subject: "Raspberry Pi Servers Update - {{ timestamp }}"
        body: |
          Update Results:
          -----------------
          Raspberry Pi servers have been successfully updated.

