---
- name: Update Redhat Servers and Send Email
  hosts: redhat_hosts
  become: true
  #become_method: sudo
  #become_user: root
  gather_facts: true
  vars:
    smtp_relay_host: "10.128.10.21"
    smtp_relay_port: 25
    smtp_sender: "ansible@internal.subterfuge.biz"
    smtp_recipient: "robert.gaines@internal.subterfuge.biz"
  tasks:
    - name: Set server name as a variable
      set_fact:
        server_name: "{{ ansible_hostname }}"

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat' or (ansible_distribution == 'Rocky' and ansible_distribution_version|int >= 8)

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
        security: yes
      when: ansible_os_family == 'RedHat' or (ansible_distribution == 'Rocky' and ansible_distribution_version|int >= 8)


    - name: Set current date and time
      set_fact:
        timestamp: "{{ ansible_date_time.date }}_{{ ansible_date_time.time }}"

    - name: Send email with update results
      community.general.mail:
        host: "{{ smtp_relay_host }}"
        port: "{{ smtp_relay_port }}"
        sender: "{{ smtp_sender }}"
        to: "{{ smtp_recipient }}"
        subject: "Redhat/Rocky Server Update - {{ timestamp }}"
        body: "Redhat/Rocky server {{ server_name }} has been successfully updated."

